<p style="font-family: Arial;font-size:2.75em;color:#FF0000;font-style:bold">
<br>
BROADCASTING
</p>

<p style="font-family: Arial;font-size:1.75em;color:#2462c0;font-style:bold">
<br>
INTRODUCTION TO BROADCASTING
</p>

# General Broadcasting Rules


When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

1. they are equal, or
2. one of them is 1

In [29]:
import numpy as np
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
#create a rank 1 nd array with 3 values
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [3]:
y=start+add_rows   #add to each row of start using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [5]:
#create an ndarray 4x1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [6]:
#add to each column of start using broadcasting
z=start+add_cols
print(z)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [7]:
#this will broadcast in both direction
add_scalar=np.array([1])
a=start+add_scalar
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<p style="font-family: Arial;font-size:1.75em;color:#2462c0;font-style:bold">
<br>
Few examples
</p>

In [10]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))
print(x)
print()
print(y)
print()
print(xx)
print()
print(z)


[0 1 2 3]

[1. 1. 1. 1. 1.]

[[0]
 [1]
 [2]
 [3]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
x.shape

(4,)

In [13]:
y.shape

(5,)

In [14]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [15]:
xx.shape

(4, 1)

In [19]:
xx+y


array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [20]:
(xx+y).shape

(4, 5)

In [21]:
x.shape

(4,)

In [22]:
z.shape

(3, 4)

In [23]:
x+z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [24]:
(x+z).shape

(3, 4)

Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

In [31]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

Here the newaxis index operator inserts a new axis into a, making it a two-dimensional 4x1 array. Combining the 4x1 array with b, which has shape (3,), yields a 4x3 array.

In [34]:
print(a)
c=np.array(a)
print(c)
c[np.newaxis,:]+b

[ 0. 10. 20. 30.]
[ 0. 10. 20. 30.]


ValueError: operands could not be broadcast together with shapes (1,4) (3,) 