# GETTING STARTED WITH NUMPY


## How to create rank1 numpy array

In [2]:
import numpy as np
an_array = np.array([3,33,333]) #create a rank 1 array
print (type(an_array))

<class 'numpy.ndarray'>


In [2]:
print (an_array.shape)

(3,)


In [3]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [5]:
an_array[0]=888     #ndarray is mutable
print(an_array)

[888  33 333]


## HOW TO CREATE RANK2 NUMPY ARRAY

In [15]:
another = np.array([[2,22,222],[1,11,111]])    # create rank2 array
print(another)                                 #print the array
print(another.shape)                           #print the shape of array
print(another[0,0],another[1,0],another[1,2])  #accessing the elements of the array

[[  2  22 222]
 [  1  11 111]]
(2, 3)
2 1 111


# CREATING DIFFERENT ARRAYS WITH PREFILLED VALUES

In [23]:
ex1=np.zeros((2,2))   #create a 2x2 array with all elements equal to 0
print(ex1)
print(ex1.shape)
print(ex1[0,0])

[[0. 0.]
 [0. 0.]]
(2, 2)
0.0


In [19]:
#create a 2x2 array filled with 7.0
ex2=np.full((2,2), 7.0)
print(ex2)
print(ex2.shape)

[[7. 7.]
 [7. 7.]]
(2, 2)


In [21]:
#create a matrix with diagonal 1s and all other 0 
ex3=np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [3]:
#create a matrix with 1s
ex4=np.ones((1,2))
print(ex4)

[[1. 1.]]


In [5]:
print(ex4.shape)   #notice the shape of ex4, it is rank 2 matrix

(1, 2)


In [6]:
#create a matrix with random values
ex5=np.random.random((2,2))
print(ex5,ex5.shape)

[[0.57144583 0.15799172]
 [0.38207333 0.94777721]] (2, 2)
