<p style="font-family: Arial;font-size:2.75em;color:#FF0000;font-style:bold">
<br>
STASTICAL METHOD,SORTING & SET OPERATION
</p>

<p style="font-family: Arial;font-size:1.75em;color:#2462c0;font-style:bold">
<br>
Basic Stastical operation
</p>

In [1]:
import numpy as np


In [4]:
# setup a random 2x4 matrix
arr=10* np.random.randn(2,4)
print(arr)

[[-6.57352381 -8.96931181 -4.57075716  4.06483718]
 [ 7.72598522  4.89536031 -9.24424688  2.59029211]]


In [5]:
# compute the mean for all elements
print(arr.mean())


-1.2601706055321493


In [11]:
# compute the mean by row
print(arr.mean(axis=1))

#compute the mean by column
print(arr.mean(axis=0))

[-4.0121889   1.49184769]
[ 0.57623071 -2.03697575 -6.90750202  3.32756465]


In [8]:
# sum of all elements
print(arr.sum())

-10.081364844257195


In [10]:
#compute the median by column
print(np.median(arr,axis=0))

[ 0.57623071 -2.03697575 -6.90750202  3.32756465]


<p style="font-family: Arial;font-size:1.75em;color:#2462c0;font-style:bold">
<br>
Sorting
</p>

In [13]:
# create a 10 random elements array
unsorted=np.random.randn(10)
print(unsorted)

[-0.01474284 -0.78620866 -1.0233173   0.69507625  1.05522636 -0.42816918
  0.02700898 -0.10027416  1.99150007  1.58657747]


In [14]:
#create copy and sort
sorted=np.array(unsorted)
sorted.sort()
print(sorted)

[-1.0233173  -0.78620866 -0.42816918 -0.10027416 -0.01474284  0.02700898
  0.69507625  1.05522636  1.58657747  1.99150007]


In [17]:
#inplace sorting
unsorted.sort()
print(unsorted)

[-1.0233173  -0.78620866 -0.42816918 -0.10027416 -0.01474284  0.02700898
  0.69507625  1.05522636  1.58657747  1.99150007]


<p style="font-family: Arial;font-size:1.75em;color:#2462c0;font-style:bold">
<br>
Finding unique elements
</p>

In [18]:
arr=np.array([1,3,2,4,2,3,4,5,5,3,2,1])
print(np.unique(arr))

[1 2 3 4 5]


<p style="font-family: Arial;font-size:1.75em;color:#2462c0;font-style:bold">
<br>
Set operation with np.array data type
</p>

In [29]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['bottle','chair','desk','bulb'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['bottle' 'chair' 'desk' 'bulb']


In [31]:
print(np.intersect1d(s1,s2))  #intersection of 2 sets
print(np.union1d(s1,s2))      #union of two sets
print(np.setdiff1d(s1,s2))    #which element of s1 is not in s2
print(np.in1d(s1,s2))         #which element of s1 is in s2


['bulb' 'chair' 'desk']
['bottle' 'bulb' 'chair' 'desk']
[]
[ True  True  True]
