In [48]:
import numpy as np
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


## Slicing of an Array

In [3]:
a_slice=an_array[:2,1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [7]:
print(a_slice[0,1])
a_slice[0,1]=10000
print(a_slice)
print(an_array) #change in the value of element in a_slice results in the change of value of element of an_array 
a_slice[0,1]=13

10000
[[   12 10000]
 [   22    23]]
[[   11    12 10000    14]
 [   21    22    23    24]
 [   31    32    33    34]]


In [9]:
a_slice=np.array(an_array[:2,1:3])     #we created a copy of the slice of an_array.So,now a_slice is just a reference.
print(a_slice)
a_slice[0,1]=1000
print(a_slice)
print(an_array)

[[12 13]
 [22 23]]
[[  12 1000]
 [  22   23]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]




## USING BOTH INTEGER AND SLICE INDEXING 
We can use different integer and slice indexing so as to create new matrices from the existing one

In [18]:
#using both integer and slicing index produces lower rank matrices.
row_rank1=an_array[1,:]

print(row_rank1,row_rank1.shape)  #Here the rank of matrix is 1 

[21 22 23 24] (4,)


In [19]:
#using slicing index produces matrix with same rank
row_rank2=an_array[1:,:]
print(row_rank2,row_rank2.shape) #Here the rank of matrix is 2

[[21 22 23 24]
 [31 32 33 34]] (2, 4)


In [21]:
#we can do the same thing for the columns
row_rank1=an_array[:,1]     #Rank=1
row_rank2=an_array[:,1:]    #Rank=2
print(row_rank1,row_rank1.shape)
print(row_rank2,row_rank2.shape)

[12 22 32] (3,)
[[12 13 14]
 [22 23 24]
 [32 33 34]] (3, 3)




## ARRAY INDEXING FOR CHANGING ELEMENTS
It's useful sometimes to access and change elements of an array using indices.

In [29]:
#create an array of indices
col_indices=np.array([0,1,0])     
row_indices=np.arange(3)
print(col_indices)
print(row_indices)
#find out the pairing of row and column indices
for row,col in zip(row_indices,col_indices):
    print(row,",",col)
    


[0 1 0]
[0 1 2]
0 , 0
1 , 1
2 , 0


In [31]:
#select one element from each row.
print(an_array[row_indices,col_indices])

[11 22 31]


In [49]:
#change the value of the elements selected
print("Before: \n",an_array)
an_array[row_indices,col_indices]+=100000
print('After:\n',an_array)




Before: 
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
After:
 [[100011     12     13     14]
 [    21 100022     23     24]
 [100031     32     33     34]]



# BOOLEAN INDEXING

### ARRAY INDEXING FOR CHANGING VALUES

In [50]:
#create a 3x2 array
an_array=np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [57]:
#create a filter which will be boolean values if the condition is met
filter=(an_array>15)
filter


array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is also an array having same dimension as the given array.

In [58]:
#now we can have an array which meets the condition.
print(an_array[filter])

[21 22 31 32]


In [62]:
#for short we could just write
an_array[an_array>15]


array([21, 22, 31, 32])

In [66]:
an_array[an_array%2==0]+=100
print(an_array)


[[ 11 312]
 [ 21 322]
 [ 31 332]]
